# Do not process generated artifacts
exclude: '^output/'

repos:
  - repo: local
    hooks:
      - id: precommit-tests-run
        name: precommit_tests_run (repo health checks)
        entry: python -m tests.precommit_tests_run --tree-max-depth 9 --init-only-nonempty --env-mode off
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]

  - repo: https://github.com/pycqa/isort
    rev: '6.0.1'
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'
    hooks:
      - id: autopep8
        args: ['-i','--exit-code','--max-line-length=120']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=lf']
