name: pymc_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.2.0
  - aeppl=0.1.4
  - aeppl-base=0.1.4
  - aesara=2.8.12
  - aesara-base=2.8.12
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aiosignal=1.3.2
  - annotated-types=0.7.0
  - appnope=0.1.4
  - arviz=0.18.0
  - asttokens=2.4.1
  - atk-1.0=2.38.0
  - attrs=25.1.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - bambi=0.13.0
  - blas=2.122
  - blas-devel=3.9.0
  - blosc=1.21.5
  - bokeh=3.4.1
  - bottleneck=1.3.8
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.14.4
  - c-compiler=1.5.2
  - ca-certificates=2025.7.9
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.3
  - cairo=1.18.0
  - catalogue=2.0.10
  - cctools=973.0.1
  - cctools_osx-arm64=973.0.1
  - certifi=2025.6.15
  - cftime=1.6.3
  - charset-normalizer=3.3.2
  - clang=14.0.6
  - clang-14=14.0.6
  - clang_osx-arm64=14.0.6
  - clangxx=14.0.6
  - clangxx_osx-arm64=14.0.6
  - click=8.1.7
  - cloudpathlib=0.21.0
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - compiler-rt=14.0.6
  - compiler-rt_osx-arm64=14.0.6
  - confection=0.1.5
  - cons=0.4.6
  - contourpy=1.2.1
  - cxx-compiler=1.5.2
  - cycler=0.12.1
  - cymem=2.0.11
  - cyrus-sasl=2.1.27
  - cython-blis=1.0.1
  - cytoolz=0.12.3
  - dask=2024.5.1
  - dask-core=2024.5.1
  - dask-expr=1.1.1
  - datasets=3.2.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - dill=0.3.8
  - distributed=2024.5.1
  - dm-tree=0.1.8
  - etuples=0.3.9
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.4
  - fastprogress=1.0.3
  - filelock=3.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.52.4
  - formulae=0.5.3
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2024.5.0
  - gdk-pixbuf=2.42.10
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - graphite2=1.3.13
  - graphviz=9.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - h5netcdf=1.3.0
  - h5py=3.13.0
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hmmlearn=0.3.3
  - huggingface_hub=0.30.2
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.24.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - langcodes=3.3.0
  - lcms2=2.15
  - ld64=609
  - ld64_osx-arm64=609
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-flight=16.1.0
  - libarrow-flight-sql=16.1.0
  - libarrow-gandiva=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp14=14.0.6
  - libcrc32c=1.1.2
  - libcurl=8.12.1
  - libcxx=19.1.7
  - libdeflate=1.17
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.84.2
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libllvm16=16.0.6
  - libllvm18=18.1.7
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libntlm=1.8
  - libopenblas=0.3.27
  - libopentelemetry-cpp=1.15.0
  - libopentelemetry-cpp-headers=1.15.0
  - libparquet=16.1.0
  - libpng=1.6.43
  - libpq=17.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librsvg=2.58.0
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libthrift=0.19.0
  - libtiff=4.5.0
  - libutf8proc=2.8.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.2.13
  - littleutils=0.2.2
  - llvm-openmp=19.1.7
  - llvm-tools=14.0.6
  - locket=1.0.0
  - logical-unification=0.4.6
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - matplotlib-venn=0.11.10
  - mdurl=0.1.2
  - minikanren=1.0.3
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - multidict=6.1.0
  - multipledispatch=0.6.0
  - multiprocess=0.70.16
  - munkres=1.1.4
  - murmurhash=1.0.10
  - mysql=8.4.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.6.5
  - nlohmann_json=3.11.3
  - nltk=3.9.1
  - numexpr=2.10.0
  - numpy=1.25.2
  - openblas=0.3.27
  - openjpeg=2.5.0
  - openldap=2.6.5
  - openssl=3.5.1
  - orc=2.0.1
  - outdated=0.2.2
  - packaging=24.0
  - pandas=2.2.2
  - pandas-flavor=0.6.0
  - pango=1.54.0
  - parso=0.8.4
  - partd=1.4.2
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pingouin=0.5.4
  - pip=24.0
  - pixman=0.44.2
  - platformdirs=4.2.2
  - ply=3.11
  - preshed=3.0.9
  - prometheus-cpp=1.2.4
  - prompt-toolkit=3.0.42
  - propcache=0.2.1
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pygments=2.18.0
  - pymc=5.15.0
  - pymc-base=5.15.0
  - pyparsing=3.1.2
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - pytables=3.9.2
  - pytensor=2.13.1
  - pytensor-base=2.20.0
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-graphviz=0.20.3
  - python-tzdata=2024.1
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - re2=2023.09.01
  - readline=8.2
  - requests=2.32.2
  - rich=13.7.1
  - safetensors=0.5.2
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=70.0.0
  - shellingham=1.5.4
  - sigtool=0.1.3
  - sip=6.10.0
  - six=1.16.0
  - smart-open=7.1.0
  - smart_open=7.1.0
  - snappy=1.2.1
  - sortedcontainers=2.4.0
  - spacy=3.8.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - spyder-kernels=2.4.4
  - sqlite=3.46.0
  - srsly=2.5.1
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - tabulate=0.9.0
  - tapi=1100.0.11
  - tblib=3.0.0
  - textblob=0.15.3
  - thinc=8.3.2
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tokenizers=0.21.0
  - tomli=2.2.1
  - toolz=0.12.1
  - tornado=6.4
  - traitlets=5.14.3
  - transformers=4.53.1
  - typer=0.15.2
  - typer-slim=0.15.2
  - typer-slim-standard=0.15.2
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ujson=5.10.0
  - urllib3=2.2.1
  - vadersentiment=3.3.2
  - wasabi=1.1.3
  - wcwidth=0.2.13
  - weasel=0.4.1
  - wheel=0.43.0
  - wrapt=1.17.2
  - wurlitzer=3.1.0
  - xarray=2024.5.0
  - xarray-einstats=0.7.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.2
  - xyzservices=2024.4.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.18.3
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - altair==5.5.0
      - blinker==1.9.0
      - datatops==0.3.1
      - dtaidistance==2.3.13
      - en-core-web-sm==3.8.0
      - flask==3.1.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - guppy3==3.1.5
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-widgets==3.0.13
      - llvmlite==0.42.0
      - more-itertools==10.2.0
      - narwhals==1.32.0
      - networkx==3.3
      - numba==0.59.1
      - openai-whisper==20240930
      - polars==0.20.31
      - protobuf==5.29.4
      - pydeck==0.9.1
      - pynndescent==0.5.13
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.0
      - referencing==0.36.2
      - regex==2024.5.15
      - rpds-py==0.24.0
      - smmap==5.0.2
      - streamlit==1.44.0
      - striprtf==0.0.29
      - sympy==1.12
      - tenacity==9.0.0
      - tiktoken==0.7.0
      - toml==0.10.2
      - torch==2.3.0
      - tqdm==4.66.4
      - tslearn==0.6.4
      - umap-learn==0.5.6
      - vibecheck==0.0.5
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
