[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = ["core"]
src_paths = ["src"]

[project]
name = "blech-intra-state-dynamics"
version = "0.0.1"
requires-python = ">=3.10"
